// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEwo32vce0kNW7sTYkN9hfUl6Y2OLwQeQ',
    appId: '1:162083529653:web:a8bff28d3f8a74705eeffc',
    messagingSenderId: '162083529653',
    projectId: 'scs-project-2025f',
    authDomain: 'scs-project-2025f.firebaseapp.com',
    storageBucket: 'scs-project-2025f.firebasestorage.app',
    measurementId: 'G-B88JMHFKWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCSIS50NogHLC4pQ-qtZYPVW7Ym0iOks',
    appId: '1:162083529653:android:d24d3aff5ba340475eeffc',
    messagingSenderId: '162083529653',
    projectId: 'scs-project-2025f',
    storageBucket: 'scs-project-2025f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9iPc-LLjLXCe3GRJ9-J7zPYdXN78F_sQ',
    appId: '1:162083529653:ios:919e16ee22f9ee705eeffc',
    messagingSenderId: '162083529653',
    projectId: 'scs-project-2025f',
    storageBucket: 'scs-project-2025f.firebasestorage.app',
    iosBundleId: 'com.example.scs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9iPc-LLjLXCe3GRJ9-J7zPYdXN78F_sQ',
    appId: '1:162083529653:ios:919e16ee22f9ee705eeffc',
    messagingSenderId: '162083529653',
    projectId: 'scs-project-2025f',
    storageBucket: 'scs-project-2025f.firebasestorage.app',
    iosBundleId: 'com.example.scs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEwo32vce0kNW7sTYkN9hfUl6Y2OLwQeQ',
    appId: '1:162083529653:web:a9730cce897ac49c5eeffc',
    messagingSenderId: '162083529653',
    projectId: 'scs-project-2025f',
    authDomain: 'scs-project-2025f.firebaseapp.com',
    storageBucket: 'scs-project-2025f.firebasestorage.app',
    measurementId: 'G-PV7KEWNSM8',
  );
}
